version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  node-app:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=alexj
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret1
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alexj
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
    volumes:
      - mongo-db:/data/db
